# Nombre del paquete
package_name: modelo-abandono

# Archivos de datos
train_data_file: bankchurn_train.csv
test_data_file: bankchurn_test.csv

# Variables
# Objetivo
target: Attrition_Flag

features:
  - Customer_Age
  - Total_Amt_Chng_Q4_Q1
  - Total_Relationship_Count
  - Total_Revolving_Bal
  - Total_Ct_Chng_Q4_Q1
  - Total_Trans_Ct
  - Total_Trans_Amt
  - Months_Inactive_12_mon
  - Contacts_Count_12_mon

temp_features:
 - Gender
 - Dependent_count
 - Education_Level
 - Marital_Status
 - Income_Category
 - Card_Category
 - Months_on_book
 - Credit_Limit
 - Avg_Open_To_Buy
 - Avg_Utilization_Ratio

# pipelines
pipeline_name: modelo-abandono
pipeline_save_file: modelo-abandono-output

# fracción del conjunto de prueba
test_size: 0.25

# semilla
random_state: 42

# hiperparámetros del modelo 
n_estimators: 850

max_depth: 19

# variables a mapear
qual_vars:
  - Attrition_Flag

# 
categorical_vars:
  - Attrition_Flag

# mapeo de variables
qual_mappings:
  Attrited Customer: 1
  Existing Customer: 0
